### ISSUE TITLE
Angående examination 2

### ISSUE THREAD

**Issue by 1dv449** [mw222rs/1DV449_mw222rs#1]
Hej!

Jag har nu tittat på din laboration 2.

Inte för jag är expert på engelska språket men det känns som en välskriven rapport som är enkel att ta del av och följa. Du identifierar de flesta problem med denna obskyra applikation och visar att du har förståelse för teorin vi gått igenom. Du uppfyller helt klart målen för examinationen och jag sätter upp dig som G?. Bra jobbat!

Det finns ett delat dokument där man kan se de olika delar som skulle kunnat tas upp i rapporten.
https://docs.google.com/document/d/1kYNrL64Od1go4z0_sZUyIG8eFAaeFcdp95MIHsRm65A/

**Comment by fyrkant** [comment]
Tack så mycket!
